### ISSUE TITLE
Ubuntu 18.04(Kernel 4.15) - Make Error

### ISSUE THREAD

**Issue by FredC88** [coolshou/rtl8814au#2]
Hi CoolShou:

Thank you very much for the effort and providing an updated RTL8814AU driver!! However, I hv the following Error when making the files, pls. take a look when you hv time. Thank you!!

* Note: I m using Edimax AC7833UAC USB wifi stick, also hv issues(other providers' Linux Drivers) on 5Ghz paring with Asus AC86u router - Cannot Activate Connection

Error Message:

TestGround/Coolshou/rtl8814au/driver/os_dep/linux/ioctl_cfg80211.c:352:2: error: implicit declaration of function ‘ktime_get_boottime_ts64’; did you mean ‘ktime_get_boottime’? [-Werror=implicit-function-declaration]
  ktime_get_boottime_ts64(&ts);
  ^~~~~~~~~~~~~~~~~~~~~~~
  ktime_get_boottime
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/joana/Desktop/TestGround/Coolshou/rtl8814au/driver/os_dep/linux/ioctl_cfg80211.o' failed
make[2]: *** [/home/joana/Desktop/TestGround/Coolshou/rtl8814au/driver/os_dep/linux/ioctl_cfg80211.o] Error 1
Makefile:1551: recipe for target '_module_/home/joana/Desktop/TestGround/Coolshou/rtl8814au/driver' failed
make[1]: *** [_module_/home/joana/Desktop/TestGround/Coolshou/rtl8814au/driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-43-generic'
Makefile:1730: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by coolshou** [comment]
sorry my mistake, the ktime_get_boottime_ts64 function introduce after kernel 4.18 not 4.15
pull the Latest commit 82049aa  to get it fix

**Comment by FredC88** [comment]
Thank you very much Sir!! It makes Successfully!!

There is still an Error while updating using DKMS, but driver is working now, at least...
