### ISSUE TITLE
modules not loading with the latest fedora kernel (5.4.14-200.fc31.x86_64)

### ISSUE THREAD

**Issue by em2xav** [coolshou/rtl8814au#7]
The latest fedora kernel (5.4.14-200.fc31.x86_64+debug)  would not load the module.
Last known good kernel (5.4.12-200.fc31.x86_64) with working wireless

Attached is the compile error/warning output:
[make.log](https://github.com/coolshou/rtl8814au/files/4141338/make.log)

Attached is the dmesg output:
[dmesg.log](https://github.com/coolshou/rtl8814au/files/4141341/dmesg.log)

**Comment by em2xav** [comment]
OK, this is selinux problem. This are the steps I used to resolved the problem under fedora ver 31
1. setenforce 0 
2. remove the wireless usb hardware, then plug back in
3.grep 8814 /var/log/audit/audit.log | audit2allow -M wireless0
4. semodule -i wireless0.pp
5. setenforce 1
6. reboot the linux

**Comment by coolshou** [comment]
think you for sharing selinux setting step.
